Print pdf
ilabafrica/blis-v3-electron-vue-app pull request #12
Opened 2019-02-04 09:01 UTC by BenOwenda

@atercode Kindly review

2019-02-12 14:33 UTC, drizzentic commented on src/components/test/index.vue
> +            // link.click()
Remove commented code.

2019-02-12 14:43 UTC, drizzentic requested changes

2019-02-12 14:43 UTC, drizzentic commented on src/components/test/index.vue
> +            // link.click()
Remove commented code.

2019-02-14 06:35 UTC, atercode commented on src/components/test/index.vue
> +            // link.click()
Removed entire section except console log as such requests are already handled by utils/api.js

2019-02-14 06:39 UTC, drizzentic approved these changes

2019-02-14 06:39 UTC, atercode approved these changes

2019-02-14 06:39 UTC, merged